name: Code Quality

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Poetry
      run: |
        pip install poetry

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true

    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: poetry-${{ hashFiles('poetry.lock') }}
        restore-keys: poetry-

    - name: Install dependencies
      run: |
        poetry install --extras dev
    
    - name: Run ruff linter
      run: |
        poetry run ruff check src/
    
    - name: Run ruff formatter check
      run: |
        poetry run ruff format --check src/
    
    - name: Run mypy type checker
      run: |
        poetry run mypy src/
    
    
    - name: Run security checks (if any security issues found)
      run: |
        # Basic security check - ensure no obvious secrets or dangerous patterns
        echo "Checking for potential security issues..."
        ! grep -r "password\|secret\|token" src/ --include="*.py" || (echo "Potential secrets found!" && exit 1)
        echo "Basic security check passed"